In [150]:
import pandas as pd

# Cargar los archivos usando la ruta correcta
level1_df = pd.read_excel('level1.xlsx')
level1_df1=level1_df.iloc[:,[0,1,2,4,6,8,10]]
level1_df1
level1_df2=level1_df1.drop([0,1,2,4,5])
level1_df2
new_header=level1_df2.iloc[0]
new_header
level1_df2.columns = new_header
level1_df2.drop(level1_df2.index[0], inplace=True)
level1_df2= level1_df2.rename(columns={'Expected years of schooling': 'EXPECT', 'Gross national income (GNI) per capita': 'GNI',"HDI rank":"HDI 2020","Life expectancy at birth":"LIFE"})
level1_df2

3,HDI 2020,Country,Human Development Index (HDI),LIFE,EXPECT,Mean years of schooling,GNI
6,1,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454
7,2,Norway,0.961,83.2339,18.1852,13.00363,64660.10622
8,3,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981
9,4,"Hong Kong, China (SAR)",0.952,85.4734,17.27817,12.22621,62606.8454
10,5,Australia,0.951,84.5265,21.05459,12.72682,49238.43335
...,...,...,...,...,...,...,...
67,62,Malaysia,0.803,74.8839,13.34304,10.64506,26657.94355
68,63,Georgia,0.802,71.694,15.56852,12.82222,14664.16825
69,63,Mauritius,0.802,73.5552,15.17353,10.42791,22025.34631
70,63,Serbia,0.802,74.1923,14.40009,11.36987,19123.02747
71,66,Thailand,0.8,78.7154,15.882219,8.69712,17030.15352

In [147]:
import pandas as pd

# Cargar los archivos usando la ruta correcta
level2_df = pd.read_excel('level2.xlsx')
level2_df=level2_df.iloc[:,[0,1,2,3,4,5,7]]
level2_df= level2_df.drop(index=0)
level2_df= level2_df.drop(index=1)
level2_df= level2_df.rename(columns={'Expected years of schooling': 'EXPECT', 'Gross national income (GNI) per capita': 'GNI',"HDI rank":"HDI 2020","Life expectancy at birth":"LIFE"})
level2_df

,HDI 2020,Country,Human Development Index (HDI),LIFE,EXPECT,Mean years of schooling,GNI
2,67.0,Albania,0.796,76.4626,14.448000,11.286455,14131.110390
3,68.0,Bulgaria,0.795,71.7980,13.897290,11.413180,23078.955950
4,68.0,Grenada,0.795,74.9362,18.662020,9.032104,13483.577400
5,70.0,Barbados,0.790,77.5714,15.713385,9.852701,12306.341000
6,71.0,Antigua and Barbuda,0.788,78.4968,14.184626,9.293741,16792.365950
7,72.0,Seychelles,0.785,71.2945,13.941610,10.283120,25830.617750
8,73.0,Sri Lanka,0.782,76.3991,14.139905,10.827300,12578.220550
9,74.0,Bosnia and Herzegovina,0.780,75.3003,13.800000,10.536320,15241.914650
10,75.0,Saint Kitts and Nevis,0.777,71.6822,15.427692,8.662745,23358.332120
11,76.0,Iran (Islamic Republic of),0.774,73.8749,14.615250,10.636453,13000.711700
12,77.0,Ukraine,0.773,71.6240,14.956569,11.131420,13255.509770
13,78.0,North Macedonia,0.770,73.8415,13.624432,10.228150,15917.752830
14,79.0,China,0.768,78.2107,14.236115,7.600118,17504.399690
15,80.0,Dominican Republic,0.767,72.6146,14.466558,9.306864,17989.600370
16,80.0,Moldova (Republic of),0.767,68.8459,14.433000,11.821590,14875.331890
17,80.0,Palau,0.767,66.0204,15.784320,12.491430,13818.678690
18,83.0,Cuba,0.764,73.6829,14.443060,12.497734,7878.847482
19,84.0,Peru,0.762,72.3769,15.387734,9.885519,12245.893660
20,85.0,Armenia,0.759,72.0431,13.116760,11.330300,13157.993900
21,86.0,Mexico,0.758,70.2127,14.864440,9.221050,17896.294980
22,87.0,Brazil,0.754,72.7504,15.599060,8.128814,14369.888480
23,88.0,Colombia,0.752,72.8296,14.442750,8.862860,14384.356660
24,89.0,Saint Vincent and the Grenadines,0.751,69.6291,14.672206,10.833430,11961.087920
25,90.0,Maldives,0.747,79.9182,12.635610,7.322000,15448.127880
26,91.0,Algeria,0.745,76.3767,14.626896,8.069284,10800.225460
27,91.0,Azerbaijan,0.745,69.3658,13.496890,10.542970,14256.744560
28,91.0,Tonga,0.745,70.9857,16.048571,11.392594,6822.031250
29,91.0,Turkmenistan,0.745,69.2644,13.210400,11.261390,13020.715500
30,95.0,Ecuador,0.740,73.6700,14.624230,8.817120,10311.632730
31,96.0,Mongolia,0.739,70.9754,14.980350,9.423700,10588.225320
32,97.0,Egypt,0.731,70.2207,13.786500,9.573026,11731.690560
33,97.0,Tunisia,0.731,73.7719,15.425382,7.431599,10257.544770
34,99.0,Fiji,0.730,67.1140,14.736790,10.921548,9980.110866
35,99.0,Suriname,0.730,70.2743,13.035644,9.776801,12672.200330
36,101.0,Uzbekistan,0.727,70.8616,12.477140,11.895590,7916.785725
37,102.0,Dominica,0.720,72.8140,13.319186,8.142186,11487.624220
38,102.0,Jordan,0.720,74.2563,10.646560,10.446680,9923.714974
39,104.0,Libya,0.718,71.9112,12.854280,7.599985,15335.712000
40,105.0,Paraguay,0.717,70.2617,12.987991,8.861840,12349.286000
41,106.0,"Palestine, State of",0.715,73.4727,13.358010,9.938480,6582.899416
42,106.0,Saint Lucia,0.715,71.1114,12.866110,8.545040,12048.303810
43,108.0,Guyana,0.714,65.6734,12.502722,8.617477,22464.657340
44,109.0,South Africa,0.713,62.3410,13.643710,11.373160,12948.373250
45,110.0,Jamaica,0.709,70.5003,13.404920,9.154629,8834.475670
46,111.0,Samoa,0.707,72.7675,12.418859,11.403800,5307.953374
47,112.0,Gabon,0.706,65.8210,12.977310,9.436000,13366.934550
48,112.0,Lebanon,0.706,75.0472,11.285870,8.718636,9525.831467
49,114.0,Indonesia,0.705,67.5703,13.748894,8.556510,11466.068360
50,115.0,Viet Nam,0.703,73.6181,12.951932,8.370280,7867.371345

In [132]:
import pandas as pd
level3_df = pd.read_excel('level3.xlsx')
level3_df=level3_df.iloc[:,[0,1,2,4,6,8,10]]
level3_df= level3_df.drop(index=1)
level3_df= level3_df.drop(index=0)
level3_df= level3_df.rename(columns={'Expected years of schooling': 'EXPECT', 'Gross national income (GNI) per capita': 'GNI',"HDI rank":"HDI 2020","Life expectancy at birth":"LIFE"})
level3_df

,HDI 2020,Country,Human Development Index (HDI),LIFE,EXPECT,Mean years of schooling,GNI
2,116.0,Philippines,0.699,69.2664,13.126570,8.969100,8920.428468
3,117.0,Botswana,0.693,61.1409,12.265138,10.340000,16198.318410
4,118.0,Bolivia (Plurinational State of),0.692,63.6304,14.946971,9.827750,8111.190194
5,118.0,Kyrgyzstan,0.692,69.9774,13.195300,11.374106,4566.303831
6,120.0,Venezuela (Bolivarian Republic of),0.691,70.5536,12.816080,11.107277,4810.882621
7,121.0,Iraq,0.686,70.3779,12.087473,7.905593,9977.249073
8,122.0,Tajikistan,0.685,71.5942,11.653036,11.333394,4547.742427
9,123.0,Belize,0.683,70.4697,12.991690,8.847600,6309.099778
10,123.0,Morocco,0.683,74.0419,14.151910,5.916000,7302.819170
11,125.0,El Salvador,0.675,70.7479,12.671348,7.150930,8295.665889
12,126.0,Nicaragua,0.667,73.8368,12.641358,7.144000,5624.793595
13,127.0,Bhutan,0.666,71.8150,13.225005,5.170262,9437.541512
14,128.0,Cabo Verde,0.662,74.0518,12.554614,6.287719,6230.200199
15,129.0,Bangladesh,0.661,72.3811,12.441980,7.379060,5472.104781
16,130.0,Tuvalu,0.641,64.5466,9.404430,10.573108,6351.435899
17,131.0,Marshall Islands,0.639,65.2688,10.239320,10.883140,4619.535393
18,132.0,India,0.633,67.2398,11.874620,6.655109,6589.980037
19,133.0,Ghana,0.632,63.7954,12.047780,8.329887,5744.504017
20,134.0,Micronesia (Federated States of),0.628,70.7100,11.549480,7.804956,3696.173945
21,135.0,Guatemala,0.627,69.2368,10.562450,5.681300,8723.285317
22,136.0,Kiribati,0.624,67.4172,11.801993,7.984462,4062.586034
23,137.0,Honduras,0.621,70.1229,10.132814,7.088480,5297.955301
24,138.0,Sao Tome and Principe,0.618,67.5912,13.365385,6.215599,4021.350815
25,139.0,Namibia,0.615,59.2690,11.927207,7.192013,8633.504452
26,140.0,Lao People's Democratic Republic,0.607,68.0608,10.136110,5.374000,7699.579617
27,140.0,Timor-Leste,0.607,67.7369,12.616098,5.436790,4460.869435
28,140.0,Vanuatu,0.607,70.4490,11.535315,7.064846,3085.411633
29,143.0,Nepal,0.602,68.4495,12.886950,5.121793,3877.315444
30,144.0,Eswatini (Kingdom of),0.597,57.0657,13.744346,5.596000,7678.591873
31,145.0,Equatorial Guinea,0.596,60.5943,9.734940,5.910863,12073.959930
32,146.0,Cambodia,0.593,69.5835,11.467720,5.088000,4078.697154
33,146.0,Zimbabwe,0.593,59.2531,12.110969,8.710909,3809.887158
34,148.0,Angola,0.586,61.6434,12.172100,5.417391,5465.617791
35,149.0,Myanmar,0.585,65.6716,10.909138,6.376800,3850.524234
36,150.0,Syrian Arab Republic,0.577,72.0627,9.164220,5.100000,4191.933893
37,151.0,Cameroon,0.576,60.3334,13.108599,6.151310,3620.932408
38,152.0,Kenya,0.575,61.4270,10.698558,6.652000,4473.570344
39,153.0,Congo,0.571,63.5187,12.330815,6.166000,2889.283521
40,154.0,Zambia,0.565,61.2234,10.928760,7.187091,3217.767739
41,155.0,Solomon Islands,0.564,70.3477,10.328690,5.711848,2481.511362
42,156.0,Comoros,0.558,63.4174,11.924324,5.078649,3142.064119
43,156.0,Papua New Guinea,0.558,65.3506,10.360771,4.740000,4008.623573
44,158.0,Mauritania,0.556,64.3636,9.376160,4.918805,5075.305711
45,159.0,CÃ´te d'Ivoire,0.550,58.5983,10.675580,5.199139,5217.448516

In [146]:
import pandas as pd

# Cargar los archivos usando la ruta correcta
level4_df = pd.read_excel('level4.xlsx')
level4_df=level4_df.iloc[:,[0,1,3,4,5,6,7]]
level4_df= level4_df.rename(columns={'Expected years of schooling': 'EXPECT', 'Gross national income (GNI) per capita': 'GNI',"HDI rank":"HDI 2020","Life expectancy at birth":"LIFE"})
level4_df

,HDI 2020,Country,Human Development Index (HDI),LIFE,EXPECT,Mean years of schooling,GNI
0,160,Tanzania (United Republic of),0.549,66.2007,9.221490,6.372899,2664.329096
1,161,Pakistan,0.544,66.0979,8.658350,4.536330,4623.705430
2,162,Togo,0.539,61.6194,12.950494,5.016807,2166.619062
3,163,Haiti,0.535,63.1924,9.700000,5.554000,2847.500746
4,163,Nigeria,0.535,52.6760,10.127584,7.181074,4790.284425
5,165,Rwanda,0.534,66.0722,11.230970,4.425292,2209.795202
6,166,Benin,0.525,59.8210,10.766680,4.304786,3408.965923
7,166,Uganda,0.525,62.7048,10.149870,5.730942,2181.436510
8,168,Lesotho,0.514,53.0620,12.040878,6.010185,2700.435748
9,169,Malawi,0.512,62.9044,12.678985,4.489695,1465.635064
10,170,Senegal,0.511,67.0926,8.963750,2.937938,3344.311825
11,171,Djibouti,0.509,62.3049,7.432980,4.100000,5024.993944
12,172,Sudan,0.508,65.2667,7.945188,3.820000,3575.190840
13,173,Madagascar,0.501,64.4853,10.134991,5.120469,1483.520983
14,174,Gambia,0.500,62.0830,9.418626,4.637487,2172.207664
15,175,Ethiopia,0.498,64.9748,9.651071,3.201521,2361.069604
16,176,Eritrea,0.492,66.5358,8.064525,4.887235,1728.742667
17,177,Guinea-Bissau,0.483,59.6523,10.613063,3.583719,1908.241590
18,178,Liberia,0.481,60.7472,10.420790,5.082000,1288.742350
19,179,Congo (Democratic Republic of the),0.479,59.1930,9.817864,7.018697,1076.098781
20,180,Afghanistan,0.478,61.9824,10.263844,2.985070,1824.190915
21,181,Sierra Leone,0.477,60.0624,9.573391,4.576081,1621.512579
22,182,Guinea,0.465,58.8922,9.805297,2.202126,2480.887182
23,183,Yemen,0.455,63.7534,9.098710,3.200000,1314.270189
24,184,Burkina Faso,0.449,59.2696,9.142100,2.114962,2117.915916
25,185,Mozambique,0.446,59.3247,10.219152,3.197642,1198.073924
26,186,Mali,0.428,58.9414,7.423038,2.310000,2132.629443
27,187,Burundi,0.426,61.6627,10.722722,3.129267,731.786709
28,188,Central African Republic,0.404,53.8947,8.040172,4.334000,966.058611
29,189,Niger,0.400,61.5763,6.957112,2.116717,1239.866936
30,190,Chad,0.394,52.5254,8.035914,2.573774,1364.169417
31,191,South Sudan,0.385,54.9752,5.542510,5.726140,767.787000

In [154]:
append_data_df = pd.concat([level1_df2, level2_df, level3_df, level4_df], ignore_index=True)
append_data_df

,HDI 2020,Country,Human Development Index (HDI),LIFE,EXPECT,Mean years of schooling,GNI
0,1,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454
1,2,Norway,0.961,83.2339,18.1852,13.00363,64660.10622
2,3,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981
3,4,"Hong Kong, China (SAR)",0.952,85.4734,17.27817,12.22621,62606.8454
4,5,Australia,0.951,84.5265,21.05459,12.72682,49238.43335
...,...,...,...,...,...,...,...
186,187,Burundi,0.426,61.6627,10.722722,3.129267,731.786709
187,188,Central African Republic,0.404,53.8947,8.040172,4.334,966.058611
188,189,Niger,0.4,61.5763,6.957112,2.116717,1239.866936
189,190,Chad,0.394,52.5254,8.035914,2.573774,1364.169417
190,191,South Sudan,0.385,54.9752,5.54251,5.72614,767.787

In [158]:
import pandas as pd
country_codes_df = pd.read_excel('countryCODES.xlsx')
country_codes_df['Country'] = country_codes_df['Country'].str.title()
country_codes_df

,Country,Officialstatename,InternetccTLD,iso2,iso3
0,Afghanistan,The Islamic Republic of Afghanistan,.af,AF,AFG
1,Albania,The Republic of Albania,.al,AL,ALB
2,Algeria,The People's Democratic Republic of Algeria,.dz,DZ,DZA
3,Angola,The Republic of Angola,.ao,AO,AGO
4,Antigua And Barbuda,Antigua and Barbuda,.ag,AG,ATG
...,...,...,...,...,...
166,Uzbekistan,The Republic of Uzbekistan,.uz,UZ,UZB
167,Viet Nam,The Socialist Republic of Viet Nam,.vn,VN,VNM
168,Yemen,The Republic of Yemen,.ye,YE,YEM
169,Zambia,The Republic of Zambia,.zm,ZM,ZMB
170,Zimbabwe,The Republic of Zimbabwe,.zw,ZW,ZWE

In [165]:
merged_df = pd.merge(append_data_df, country_codes_df, on='Country', how='left')
merged_df= merged_df.drop(index=3)
merged_df= merged_df.drop(index=187)
merged_df= merged_df.drop(index=188)
merged_df

,HDI 2020,Country,Human Development Index (HDI),LIFE,EXPECT,Mean years of schooling,GNI,Officialstatename,InternetccTLD,iso2,iso3
0,1,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454,The Swiss Confederation,.ch,CH,CHE
1,2,Norway,0.961,83.2339,18.1852,13.00363,64660.10622,The Kingdom of Norway,.no,NO,NOR
2,3,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981,Iceland,.is,IS,ISL
4,5,Australia,0.951,84.5265,21.05459,12.72682,49238.43335,The Commonwealth of Australia,.au,AU,AUS
5,6,Denmark,0.948,81.3753,18.7148,12.96049,60364.78595,The Kingdom of Denmark,.dk,DK,DNK
...,...,...,...,...,...,...,...,...,...,...,...
184,185,Mozambique,0.446,59.3247,10.219152,3.197642,1198.073924,The Republic of Mozambique,.mz,MZ,MOZ
185,186,Mali,0.428,58.9414,7.423038,2.31,2132.629443,The Republic of Mali,.ml,ML,MLI
186,187,Burundi,0.426,61.6627,10.722722,3.129267,731.786709,The Republic of Burundi,.bi,BI,BDI
189,190,Chad,0.394,52.5254,8.035914,2.573774,1364.169417,The Republic of Chad,.td,TD,TCD
190,191,South Sudan,0.385,54.9752,5.54251,5.72614,767.787,The Republic of South Sudan,.ss,SS,SSD

In [173]:
import pandas as pd
fallecidos_df = pd.read_csv('fallecidosCOVID.csv')
# Asumiendo que la columna concatenada se llama 'columna_concatenada'
columnas = ['FECHA_CORTE','FECHA_FALLECIMIENTO','EDAD_DECLARADA','SEXO','CLASIFICACION_DEF','DEPARTAMENTO','PROVINCIA','DISTRITO','UBIGEO','UUID']
fallecidos_df[columnas] = fallecidos_df['FECHA_CORTE;FECHA_FALLECIMIENTO;EDAD_DECLARADA;SEXO;CLASIFICACION_DEF;DEPARTAMENTO;PROVINCIA;DISTRITO;UBIGEO;UUID'].str.split(';', expand=True)
# Eliminar la columna original
fallecidos_df = fallecidos_df.drop(columns=['FECHA_CORTE;FECHA_FALLECIMIENTO;EDAD_DECLARADA;SEXO;CLASIFICACION_DEF;DEPARTAMENTO;PROVINCIA;DISTRITO;UBIGEO;UUID'])
fallecidos_df

,FECHA_CORTE,FECHA_FALLECIMIENTO,EDAD_DECLARADA,SEXO,CLASIFICACION_DEF,DEPARTAMENTO,PROVINCIA,DISTRITO,UBIGEO,UUID
0,20240317,20220219,63,MASCULINO,Criterio virolÃ³gico,TUMBES,TUMBES,TUMBES,240101,203506
1,20240317,20210529,74,MASCULINO,Criterio virolÃ³gico,TUMBES,TUMBES,TUMBES,240101,203532
2,20240317,20210623,72,FEMENINO,Criterio SINADEF,TACNA,TACNA,ALTO DE LA ALIANZA,230102,203584
3,20240317,20210824,85,MASCULINO,Criterio investigaciÃ³n EpidemiolÃ³gica,TUMBES,TUMBES,TUMBES,240101,212541
4,20240317,20210627,46,MASCULINO,Criterio virolÃ³gico,TACNA,TACNA,ALTO DE LA ALIANZA,230102,203665
...,...,...,...,...,...,...,...,...,...,...
220913,20240317,20200809,77,MASCULINO,Criterio radiolÃ³gico,AREQUIPA,AREQUIPA,ALTO SELVA ALEGRE,040102,
220914,20240317,20201028,81,MASCULINO,Criterio clÃ­nico,LAMBAYEQUE,CHICLAYO,CHICLAYO,140101,
220915,20240317,20200515,68,FEMENINO,Criterio SINADEF,LIMA,LIMA,LA MOLINA,150114,
220916,20240317,20210414,66,FEMENINO,Criterio clÃ­nico,LIMA,LIMA,LOS OLIVOS,150117,
220917,20240317,20200819,61,MASCULINO,Criterio nexo epidemiolÃ³gico,PIURA,PIURA,TAMBO GRANDE,200114,

In [177]:
import pandas as pd

fallecidos_df = pd.read_csv('fallecidosCOVID.csv')

columnas = ['FECHA_CORTE','FECHA_FALLECIMIENTO','EDAD_DECLARADA','SEXO','CLASIFICACION_DEF','DEPARTAMENTO','PROVINCIA','DISTRITO','UBIGEO','UUID']
fallecidos_df[columnas] = fallecidos_df['FECHA_CORTE;FECHA_FALLECIMIENTO;EDAD_DECLARADA;SEXO;CLASIFICACION_DEF;DEPARTAMENTO;PROVINCIA;DISTRITO;UBIGEO;UUID'].str.split(';', expand=True)

fallecidos_df = fallecidos_df.drop(columns=['FECHA_CORTE;FECHA_FALLECIMIENTO;EDAD_DECLARADA;SEXO;CLASIFICACION_DEF;DEPARTAMENTO;PROVINCIA;DISTRITO;UBIGEO;UUID'])
fallecidos_df['FECHA_FALLECIMIENTO'] = pd.to_datetime(fallecidos_df['FECHA_FALLECIMIENTO'], format='%Y%m%d', errors='coerce')

fallecidos_df['YearMonth'] = fallecidos_df['FECHA_FALLECIMIENTO'].dt.strftime('%Y-%m')

reporte_mensual = fallecidos_df.groupby('YearMonth')['UUID'].count().reset_index()

reporte_mensual.columns = ['YearMonth', 'Fallecidos']

reporte_mensual

   YearMonth  Fallecidos
0    2020-03         181
1    2020-04        5134
2    2020-05       16363
3    2020-06       17462
4    2020-07       18501
5    2020-08       17668
6    2020-09        8437
7    2020-10        4471
8    2020-11        3229
9    2020-12        3885
10   2021-01       11175
11   2021-02       18645
12   2021-03       20691
13   2021-04       23110
14   2021-05       16692
15   2021-06        7722
16   2021-07        3481
17   2021-08        1850
18   2021-09        1140
19   2021-10        1066
20   2021-11        1107
21   2021-12        1283
22   2022-01        3562
23   2022-02        3503
24   2022-03        1299
25   2022-04         741
26   2022-05         625
27   2022-06         542
28   2022-07        1025
29   2022-08        1429
30   2022-09         892
31   2022-10         429
32   2022-11         272
33   2022-12         423
34   2023-01         371
35   2023-02         287
36   2023-03         295
37   2023-04         337
38   2023-05         323
39   2023-06         291
40   2023-07         258
41   2023-08         249
42   2023-09          60
43   2023-10          26
44   2023-11          33
45   2023-12          40
46   2024-01         249
47   2024-02          62
48   2024-03           2

In [181]:
import pandas as pd

fallecidos_df = pd.read_csv('fallecidosCOVID.csv')

columnas = ['FECHA_CORTE','FECHA_FALLECIMIENTO','EDAD_DECLARADA','SEXO','CLASIFICACION_DEF','DEPARTAMENTO','PROVINCIA','DISTRITO','UBIGEO','UUID']
fallecidos_df[columnas] = fallecidos_df['FECHA_CORTE;FECHA_FALLECIMIENTO;EDAD_DECLARADA;SEXO;CLASIFICACION_DEF;DEPARTAMENTO;PROVINCIA;DISTRITO;UBIGEO;UUID'].str.split(';', expand=True)

fallecidos_df = fallecidos_df.drop(columns=['FECHA_CORTE;FECHA_FALLECIMIENTO;EDAD_DECLARADA;SEXO;CLASIFICACION_DEF;DEPARTAMENTO;PROVINCIA;DISTRITO;UBIGEO;UUID'])

fallecidos_df['FECHA_FALLECIMIENTO'] = pd.to_datetime(fallecidos_df['FECHA_FALLECIMIENTO'], format='%Y%m%d', errors='coerce')

fallecidos_df['YearMonth'] = fallecidos_df['FECHA_FALLECIMIENTO'].dt.strftime('%Y-%m')

reporte_mensual = pd.pivot_table(fallecidos_df, values='UUID', index='YearMonth', columns='CLASIFICACION_DEF', aggfunc='count', fill_value=0)

reporte_mensual = reporte_mensual.rename(columns={'UUID': 'Fallecidos'})
reporte_mensual=reporte_mensual.iloc[:,[0,1,2,3,4,6]]

reporte_mensual

CLASIFICACION_DEF,Criterio SINADEF,Criterio clÃ­nico,Criterio investigaciÃ³n EpidemiolÃ³gica,Criterio nexo epidemiolÃ³gico,Criterio radiolÃ³gico,Criterio virolÃ³gico
YearMonth,,,,,,
2020-03,35,52,25,2,7,58
2020-04,1793,541,498,68,182,1274
2020-05,6826,1152,1427,203,480,3042
2020-06,5722,670,1706,251,391,3117
2020-07,5012,609,1512,262,415,3190
2020-08,4589,611,1456,208,534,2870
2020-09,1984,475,755,105,233,1402
2020-10,1091,463,469,50,172,809
2020-11,704,462,307,37,186,666
2020-12,802,547,171,41,179,1098
2021-01,2190,514,323,107,434,5159
2021-02,4993,501,465,150,556,9441
2021-03,6100,525,517,229,456,11161
2021-04,7450,748,591,246,363,12224
2021-05,5225,628,349,155,283,8877
2021-06,2723,116,123,51,138,3825
2021-07,1025,113,67,35,68,1652
2021-08,578,75,22,15,36,837
2021-09,554,12,0,0,0,384
2021-10,469,12,0,0,0,437
2021-11,441,16,0,0,0,493
2021-12,585,8,0,0,0,557
2022-01,1894,22,0,0,0,1605
2022-02,1604,20,0,0,0,1878
2022-03,352,6,0,0,0,941
2022-04,131,9,0,0,0,601
2022-05,85,3,0,0,0,537
2022-06,81,3,0,0,0,458
2022-07,299,3,0,0,0,723
2022-08,405,6,0,0,0,1018
2022-09,154,12,0,0,0,726
2022-10,53,59,0,0,0,317
2022-11,23,0,0,0,0,249
2022-12,66,0,0,0,0,357
2023-01,34,1,0,0,0,336
2023-02,4,0,0,0,0,283
2023-03,6,0,0,0,0,289
2023-04,17,0,0,0,0,320
2023-05,6,0,0,0,0,317
2023-06,2,0,0,0,0,289
2023-07,3,0,0,0,0,255
2023-08,7,0,0,0,0,242
2023-09,7,0,0,0,0,53
2023-10,8,0,0,0,0,18
2023-11,13,0,0,0,0,20
2023-12,17,0,0,0,0,22
2024-01,35,0,0,0,0,83
2024-02,1,0,0,0,0,45
2024-03,0,0,0,0,0,2